import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { StickyNavbar } from "@/components/navbar";

const poppins = Poppins({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#7c9afd] " style={poppins.style}>
        <div className="container mx-auto min-h-screen w-[calc(100%+48px)]  flex flex-col overflow-x-hidden text-white">
          <StickyNavbar />
          <main className=" grow ">{children}</main>
        </div>
      </body>
    </html>
  );
}
